### ISSUE TITLE
Get TypeError: module.exportDefault is not a function, after update meteor

### ISSUE THREAD

**Issue by liu0fanyi** [englue/meteor-publish-composite#107]
this is the update info:
```
diff --git a/.meteor/packages b/.meteor/packages
index b7fad86..53adff4 100644
--- a/.meteor/packages
+++ b/.meteor/packages
@@ -13,14 +13,13 @@ tracker@1.1.3                 # Meteor's client-side reactive programming librar

 standard-minifier-css@1.3.4   # CSS minifier run for production mode
 es5-shim@4.6.15                # ECMAScript 5 compatibility for older browsers.
-ecmascript@0.7.3              # Enable ECMAScript2015+ syntax in app code
+ecmascript@0.8.0-rc.7              # Enable ECMAScript2015+ syntax in app code

 accounts-password@1.3.6
 check@1.2.5
 audit-argument-checks@1.0.7

-fourseven:scss
-aldeed:collection2
+fourseven:scss@4.5.0
 alanning:roles
 themeteorchef:bert
 static-html@1.1.11
@@ -40,8 +39,19 @@ github-config-ui@1.0.0
 ostrio:files
 random@1.0.10
 kadira:dochead
-okgrow:analytics
+okgrow:analytics@3.0.0
 gadicohen:sitemaps
 jazeee:spiderable-longer-timeout
 abernix:standard-minifier-js
 votercircle:winston
+accounts-base@1.3.0
+aldeed:collection2-core@2.0.0
+aldeed:schema-deny
+aldeed:schema-index
+babel-compiler@6.20.0-pre.1
+localstorage@1.2.0-pre.1
+modules@0.10.0-pre.1
+modules-runtime@0.9.0-pre.1
+ecmascript-runtime-client@0.5.0-pre.1
+ecmascript-runtime-server@0.5.0-pre.1
+ecmascript-runtime@0.4.1-rc.7
```

and error:
```
W20170527-09:56:52.295(8)? (STDERR) /Users/mac/.meteor/packages/meteor-tool/.1.4.4_2.1nknj64++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20170527-09:56:52.295(8)? (STDERR) 			throw(ex);
W20170527-09:56:52.296(8)? (STDERR) 			^
W20170527-09:56:52.297(8)? (STDERR)
W20170527-09:56:52.297(8)? (STDERR) TypeError: module.exportDefault is not a function
W20170527-09:56:52.298(8)? (STDERR)     at meteorInstall.node_modules.meteor.reywood:publish-composite.lib.published_document.js (packages/reywood:publish-composite/lib/published_document.js:1:8)
W20170527-09:56:52.298(8)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:333:9)
W20170527-09:56:52.299(8)? (STDERR)     at require (packages/modules-runtime.js:228:16)
W20170527-09:56:52.299(8)? (STDERR)     at meteorInstall.node_modules.meteor.reywood:publish-composite.lib.published_document_list.js (packages/reywood:publish-composite/lib/published_document_list.js:1:108)
W20170527-09:56:52.300(8)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:333:9)
W20170527-09:56:52.300(8)? (STDERR)     at require (packages/modules-runtime.js:228:16)
W20170527-09:56:52.300(8)? (STDERR)     at meteorInstall.node_modules.meteor.reywood:publish-composite.lib.publication.js (packages/reywood:publish-composite/lib/publication.js:1:392)
W20170527-09:56:52.301(8)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:333:9)
W20170527-09:56:52.301(8)? (STDERR)     at require (packages/modules-runtime.js:228:16)
W20170527-09:56:52.301(8)? (STDERR)     at meteorInstall.node_modules.meteor.reywood:publish-composite.lib.publish_composite.js (packages/reywood:publish-composite/lib/publish_composite.js:1:282)
```

want help....thanks!

**Comment by reywood** [comment]
Sorry for delay in getting back to you. Could be related to babel compilation? Not sure. If it's still a problem and you can put together a repo that demonstrates the problem, I'll take a look. Closing for now, but will reopen if I hear anything.
