### ISSUE TITLE
Exception - Can't call observeChanges from an observe callback on the same query 

### ISSUE THREAD

**Issue by DeanKamali** [englue/meteor-publish-composite#116]
I'm trying to publish a subset of Meteor.users collection data,  particularly users with assigned admin role

```
import { Meteor } from 'meteor/meteor';
import { publishComposite } from 'meteor/reywood:publish-composite';
    
    // We create our publication on the server. Note the "collectionName" option.
    Meteor.publishComposite("usersnew", {
        find: () => {
            return Meteor.users.find({});
        },
        children: [
            {
                // Here we specify the client-side collection name we would
                // like to publish these records to.
                collectionName: "Admins",

                find: ()  => {
                    return Meteor.users.find({ 'roles': 'admin'});
                }
            }
        ]
    });
```

No data showing in client-side collection named "Admins", Meteor version 1.6

```
Exception in callback of async function: Error: Can't call observeChanges from an observe callback on the same query
I20180331-13:10:53.692(-4)?     at ObserveMultiplexer.addHandleAndSendInitialAdds (packages/mongo/observe_multiplex.js:40:13)
I20180331-13:10:53.692(-4)?     at MongoConnection._observeChanges (packages/mongo/mongo_driver.js:1268:15)
I20180331-13:10:53.692(-4)?     at Cursor.observeChanges (packages/mongo/mongo_driver.js:935:22)
I20180331-13:10:53.693(-4)?     at Object.result.(anonymous function) [as observeChanges] (packages/maximum_reactive-cursors.js:49:27)
I20180331-13:10:53.693(-4)?     at packages/maximum_reactive-cursors.js:72:33
I20180331-13:10:53.693(-4)?     at Object.Tracker.nonreactive (packages/peerlibrary_server-autorun/server.coffee:190:12)
I20180331-13:10:53.693(-4)?     at Cursor.observeChanges (packages/maximum_reactive-cursors.js:70:24)
I20180331-13:10:53.693(-4)?     at Function.LocalCollection._observeFromObserveChanges (packages/minimongo/local_collection.js:1333:25)
I20180331-13:10:53.693(-4)?     at Cursor.observe (packages/mongo/mongo_driver.js:911:26)
I20180331-13:10:53.693(-4)?     at Publication.publish (packages/reywood:publish-composite/lib/publication.js:34:42)
```

Any ideas?

**Comment by DeanKamali** [comment]
False alarm, restarting meteor fixed the issue
