### ISSUE TITLE
Publication error

### ISSUE THREAD

**Issue by ccorcos** [englue/meteor-publish-composite#30]
I check to see if a user is logged in to publish:

```
Meteor.publishComposite 'records', () ->
  if @userId
    return {
      find: ->
        r = Records.find {ownerId: @userId}
        if r then return r else return false
      children: [{
        find: (record) ->
          if record?.receiptId?
            Receipts.find record.receiptId
        }]}
  else
    return {}
```

And sometime, like when I logout, I get a weird error like this:

```
I20150121-17:46:30.854(-8)? Exception from sub nm4iMHFpRBzNsgsp4 TypeError: Cannot call method 'apply' of undefined
I20150121-17:46:30.856(-8)?     at [object Object].Publication._getCursor (packages/reywood:publish-composite/lib/publication.js:76:1)
I20150121-17:46:30.856(-8)?     at [object Object].Publication.publish (packages/reywood:publish-composite/lib/publication.js:11:1)
I20150121-17:46:30.856(-8)?     at [object Object].<anonymous> (packages/reywood:publish-composite/lib/publish_composite.js:12:1)
I20150121-17:46:30.856(-8)?     at packages/matb33:collection-hooks/collection-hooks.js:218:1
I20150121-17:46:30.856(-8)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150121-17:46:30.857(-8)?     at [object Object]._handler (packages/matb33:collection-hooks/collection-hooks.js:217:1)
I20150121-17:46:30.857(-8)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1599:1)
I20150121-17:46:30.857(-8)?     at [object Object]._.extend._runHandler (packages/ddp/livedata_server.js:943:1)
I20150121-17:46:30.857(-8)?     at packages/ddp/livedata_server.js:737:1
I20150121-17:46:30.857(-8)?     at Function._.each._.forEach (packages/underscore/underscore.js:113:1)
```

**Comment by benstr** [comment]
Here is an example of how I do it by calling `this.stop()` in the else.

```
Meteor.publishComposite "equipment", ->
  if @userId
    find: ->
      Equipment.find {},
        sort:
          name: 1
        fields:
          name: 1
          equipType: 1
  else
    # user not authorized. do not publish secrets
    @stop()
    return
```

**Comment by reywood** [comment]
The best way to do this is to move your user check inside the `find` function.

```
Meteor.publishComposite 'records', () ->
  return {
    find: ->
      if @userId
        r = Records.find {ownerId: @userId}
        if r then return r else return false
    children: [{
      find: (record) ->
        if record?.receiptId?
          Receipts.find record.receiptId
      }]}
```

You should not call `@stop` when using publishComposite.

**Comment by benstr** [comment]
OK thanks for noting that @reywood

**Comment by ccorcos** [comment]
Thanks @reywood. I forgot to remove `if r then return r else return false` before posting -- that we me just trying different things. Thanks again.
