### ISSUE TITLE
Error when logging out

### ISSUE THREAD

**Issue by patrickml** [englue/meteor-publish-composite#46]
for some reason I am receiving this error when logging out:

~~~
I20150707-10:23:10.082(-4)? Exception from sub projects id Hr8aJgXRcEsFnDSDQ TypeError: Cannot read property 'children' of undefined
I20150707-10:23:10.082(-4)?     at new Publication (/Users/patricklewis/Documents/sites/meteor/bace/app/.meteor/local/build/programs/server/packages/reywood_publish-composite.js:61:35)
I20150707-10:23:10.082(-4)?     at [object Object].<anonymous> (/Users/patricklewis/Documents/sites/meteor/bace/app/.meteor/local/build/programs/server/packages/reywood_publish-composite.js:423:19)
I20150707-10:23:10.083(-4)?     at /Users/patricklewis/Documents/sites/meteor/bace/app/.meteor/local/build/programs/server/packages/matb33_collection-hooks.js:242:21
I20150707-10:23:10.083(-4)?     at [object Object]._.extend.withValue (/Users/patricklewis/Documents/sites/meteor/bace/app/.meteor/local/build/programs/server/packages/meteor.js:989:17)
I20150707-10:23:10.083(-4)?     at [object Object]._handler (/Users/patricklewis/Documents/sites/meteor/bace/app/.meteor/local/build/programs/server/packages/matb33_collection-hooks.js:241:28)
I20150707-10:23:10.083(-4)?     at maybeAuditArgumentChecks (/Users/patricklewis/Documents/sites/meteor/bace/app/.meteor/local/build/programs/server/packages/ddp.js:2445:12)
I20150707-10:23:10.083(-4)?     at [object Object]._.extend._runHandler (/Users/patricklewis/Documents/sites/meteor/bace/app/.meteor/local/build/programs/server/packages/ddp.js:1778:17)
I20150707-10:23:10.083(-4)?     at [object Object].MeteorX.Subscription._runHandler (/Users/patricklewis/Documents/sites/meteor/bace/app/.meteor/local/build/programs/server/packages/meteorhacks_unblock.js:61:22)
I20150707-10:23:10.084(-4)?     at [object Object].MeteorX.Session._startSubscription (/Users/patricklewis/Documents/sites/meteor/bace/app/.meteor/local/build/programs/server/packages/meteorhacks_unblock.js:49:7)
I20150707-10:23:10.084(-4)?     at [object Object]._.extend.protocol_handlers.sub (/Users/patricklewis/Documents/sites/meteor/bace/app/.meteor/local/build/programs/server/packages/ddp.js:1410:12)
I20150707-10:23:10.084(-4)?     at [object Object].MeteorX.Session.protocol_handlers.sub (/Users/patricklewis/Documents/sites/meteor/bace/app/.meteor/local/build/programs/server/packages/meteorhacks_unblock.js:23:15)
I20150707-10:23:10.084(-4)?     at /Users/patricklewis/Documents/sites/meteor/bace/app/.meteor/local/build/programs/server/packages/ddp.js:1374:43
~~~

 I have a feeling it has to do the fact that I have a check for if you are logged in in the publish function like so

~~~
Meteor.publishComposite('project', function (_id) {
  if(!this.userId)
    return;
~~~

Any ideas?

**Comment by reywood** [comment]
Fix merged and deployed
