### ISSUE TITLE
Object has no method _getCollectionName

### ISSUE THREAD

**Issue by rfines** [englue/meteor-publish-composite#51]
I am receiving the above error and the following output:

    TypeError: Object  has no method '_getCollectionName'
    W20150728-18:13:33.322(-5)? (STDERR)   at Publication._getCollectionName   (/Users/rfines/Projects/eventr.io/.meteor/local/build/programs/server/packages/reywood_publish-composite.js:130:63)
    W20150728-18:13:33.322(-5)? (STDERR)   at Publication.unpublish (/Users/rfines/Projects/eventr.io/.meteor/local/build/programs/server/packages/reywood_publish-composite.js:108:44)
    W20150728-18:13:33.322(-5)? (STDERR)   at /Users/rfines/Projects/eventr.io/.meteor/local/build/programs/server/packages/reywood_publish-composite.js:186:21
    W20150728-18:13:33.323(-5)? (STDERR)   at [object Object].eachChildPub (/Users/rfines/Projects/eventr.io/.meteor/local/build/programs/server/packages/reywood_publish-composite.js:282:9)
    W20150728-18:13:33.323(-5)? (STDERR)   at [object Object].eachChildPub (/Users/rfines/Projects/eventr.io/.meteor/local/build/programs/server/packages/reywood_publish-composite.js:240:13)
    W20150728-18:13:33.323(-5)? (STDERR)   at Publication._unpublishChildrenOf (/Users/rfines/Projects/eventr.io/.meteor/local/build/programs/server/packages/reywood_publish-composite.js:185:24)
    W20150728-18:13:33.323(-5)? (STDERR)   at Publication._removeDoc (/Users/rfines/Projects/eventr.io/.meteor/local/build/programs/server/packages/reywood_publish-composite.js:178:10)
    W20150728-18:13:33.323(-5)? (STDERR)   at Publication.<anonymous> (/Users/rfines/Projects/eventr.io/.meteor/local/build/programs/server/packages/reywood_publish-composite.js:150:14)
    W20150728-18:13:33.324(-5)? (STDERR)   at Publication.execCallbackOnDoc (/Users/rfines/Projects/eventr.io/.meteor/local/build/programs/server/packages/reywood_publish-composite.js:232:18)
    W20150728-18:13:33.324(-5)? (STDERR)   at Function._.each._.forEach (/Users/rfines/Projects/eventr.io/.meteor/local/build/programs/server/packages/underscore.js:147:22)
    W20150728-18:13:33.324(-5)? (STDERR)   at [object Object].eachDocument (/Users/rfines/Projects/eventr.io/.meteor/local/build/programs/server/packages/reywood_publish-composite.js:231:7)
    W20150728-18:13:33.324(-5)? (STDERR)   at Publication._unpublishAllDocuments (/Users/rfines/Projects/eventr.io/.meteor/local/build/programs/server/packages/reywood_publish-composite.js:149:24)
    W20150728-18:13:33.324(-5)? (STDERR)   at Publication.unpublish (/Users/rfines/Projects/eventr.io/.meteor/local/build/programs/server/packages/reywood_publish-composite.js:110:10)
    W20150728-18:13:33.324(-5)? (STDERR)   at /Users/rfines/Projects/eventr.io/.meteor/local/build/programs/server/packages/reywood_publish-composite.js:427:17
    W20150728-18:13:33.324(-5)? (STDERR)   at /Users/rfines/Projects/eventr.io/.meteor/local/build/programs/server/packages/ddp.js:1882:7
    W20150728-18:13:33.324(-5)? (STDERR)   at Array.forEach (native)
    W20150728-18:13:33.324(-5)? (STDERR)   at Function._.each._.forEach (/Users/rfines/Projects/eventr.io/.meteor/local/build/programs/server/packages/underscore.js:139:11)
    W20150728-18:13:33.325(-5)? (STDERR)   at [object Object]._.extend._callStopCallbacks (/Users/rfines/Projects/eventr.io/.meteor/local/build/programs/server/packages/ddp.js:1881:7)
    W20150728-18:13:33.325(-5)? (STDERR)   at [object Object]._.extend._deactivate (/Users/rfines/Projects/eventr.io/.meteor/local/build/programs/server/packages/ddp.js:1871:10)
    W20150728-18:13:33.325(-5)? (STDERR)   at [object Object].subscriptionProto._deactivate (/Users/rfines/Projects/eventr.io/.meteor/local/build/programs/server/packages/meteorhacks_kadira.js:2646:24)
    W20150728-18:13:33.325(-5)? (STDERR)   at [object Object]._.extend._stopSubscription (/Users/rfines/Projects/eventr.io/.meteor/local/build/programs/server/packages/ddp.js:1609:30)
    W20150728-18:13:33.325(-5)? (STDERR)   at [object Object]._.extend.protocol_handlers.unsub (/Users/rfines/Projects/eventr.io/.meteor/local/build/programs/server/packages/ddp.js:1417:12)
    W20150728-18:13:33.325(-5)? (STDERR)   at [object Object].sessionProto.protocol_handlers.unsub (/Users/rfines/Projects/eventr.io/.meteor/local/build/programs/server/packages/meteorhacks_kadira.js:2464:40)
    W20150728-18:13:33.325(-5)? (STDERR)   at /Users/rfines/Projects/eventr.io/.meteor/local/build/programs/server/packages/ddp.js:1374:43

from a publication that looks like:

    Meteor.publishComposite('estimates', function() {
  	return {
	    find: function() {
	    	
	    	
	    	var c = Companies.findOne({$or:[{
				createdBy:this.userId
			},{
				authorizedUsers:{$in:[this.userId]}
			}]});
			if(c){
	      		return Estimates.find({$or:[{vendorApprover:c._id},{exhibitorApprover:c._id}]});
	      	}
	    },
	    children: [
	      	{
	        	find: function(estimate) {
	          		return Files.find({_id: {$in: estimate.files || []}});
	        	}
	      	},
	      	
	  		{
	        	find: function(estimate) {
	          		return CartItems.find({_id:estimate.cartItemId});
	        	},
	        	children:[
	        		{
		        		find:function(ci, estimate){
		        			return Booths.find({_id: ci.boothId});
		        		}	
	        		},
	        		{
		        		find:function(ci, estimate){
		        			return Products.find({_id: ci.product._id});
		        		}
		        	},
		        	{
		        		find:function(ci, estimate){
	        				return Shows.find({_id:ci.showId});
	        			}
		        	},
		        	{
			        	find: function(ci,estimate) {
			          		return Carts.find({_id: ci.cartId});
			        	},
			        
			      	},
	        	]

	  		},
	  		{
	      		find:function(estimate){
	      			return Companies.find({_id:{$in:[estimate.vendorApprover, estimate.exhibitorApprover]}});
	      		}
			},
    	]
  	}
    });

It is dramatically affecting the loading times of the page it is on, though the documents do eventually get published to the client, it takes a minute or so for them to appear. Can you give me any guidance on what I might be doing wrong?

**Comment by rfines** [comment]
I have created a (gist)[https://gist.github.com/rfines/c0cde63eb4198da22d11] that has some more console output for you to look over if it is helpful. I recently updated my packages and this started happening at almost every composite publication that the client subscribes to. The first time I visit any page that relies on a composite publication I get a bunch of error output in my console and the page never renders. After I visited the page once and refresh or return to the page, the page renders as expected.

I would appreciate any help you can give me.

**Comment by rfines** [comment]
Apparently returning nothing from a find function is not the same as returning a falsey value. Also I couldn't return a cursor that I knew to be empty, something like:

    return Files.find({_id:"null"});

That doesn't work but
  
    return;

does seem to make the error go away. So I had to change all of my publishComposite publications that had cases that didn't return anything from the find function to have an else case like so:

    if(somecaseistrue){
        return Files.find({somefield:somevalue});
    }else{
        return;
    }

Just thought I would update this for anyone who might stumble upon it in the future.
