### ISSUE TITLE
METEOR@1.2-rc.9 issue

### ISSUE THREAD

**Issue by jasonxeno** [englue/meteor-publish-composite#57]
My publish composites used to work in Meteor 1.1.0.3 but with Meteor release/METEOR@1.2-rc.9, I'm getting the following error.

I20150831-15:29:11.360(-5)? Exception in queued task: TypeError: Cannot read property '_id' of undefined
I20150831-15:29:11.360(-5)?     at [object Object].children.find (server/publications/shipments.js:129:1)
I20150831-15:29:11.360(-5)?     at Publication._getCursor (packages/reywood_publish-composite/packages/reywood_publish-composite.js:117:1)
I20150831-15:29:11.361(-5)?     at Publication.publish (packages/reywood_publish-composite/packages/reywood_publish-composite.js:58:1)
I20150831-15:29:11.361(-5)?     at Publication.createChildPublication (packages/reywood_publish-composite/packages/reywood_publish-composite.js:128:1)
I20150831-15:29:11.361(-5)?     at Array.forEach (native)
I20150831-15:29:11.361(-5)?     at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
I20150831-15:29:11.361(-5)?     at Publication._publishChildrenOf (packages/reywood_publish-composite/packages/reywood_publish-composite.js:125:1)
I20150831-15:29:11.361(-5)?     at Object.added (packages/reywood_publish-composite/packages/reywood_publish-composite.js:77:1)
I20150831-15:29:11.361(-5)?     at [object Object].observeChangesCallbacks.added (packages/minimongo/observe.js:153:1)
I20150831-15:29:11.361(-5)?     at self.applyChange.added (packages/minimongo/observe.js:53:1)
I20150831-15:29:11.361(-5)?     at packages/mongo/observe_multiplex.js:183:1
I20150831-15:29:11.361(-5)?     at Array.forEach (native)
I20150831-15:29:11.361(-5)?     at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
I20150831-15:29:11.362(-5)?     at Object.task (packages/mongo/observe_multiplex.js:177:1)
I20150831-15:29:11.362(-5)?     at [object Object]._.extend._run (packages/meteor/fiber_helpers.js:147:1)
I20150831-15:29:11.362(-5)?     at packages/meteor/fiber_helpers.js:125:1

**Comment by jasonxeno** [comment]
Nevermind, it is not this package's issue.
