### ISSUE TITLE
Value of null

### ISSUE THREAD

**Issue by GJean** [englue/meteor-publish-composite#61]
Hello, 

I have this code : 
```javascript
Meteor.publishComposite('devisListAll', function (query, options, limit) {
    options.limit = limit;
    query = query || {};
    return {
        find: function () {
            return Devis.find(query, options);
        },
        children: [
            {
                find: function (devis) {
                    console.log(Client.find({code: devis.codeClient}, {fields: {nom: 1, code: 1}}).fetch());
                    return Client.find({code: devis.codeClient}, {fields: {nom: 1, code: 1}});
                }
            }
        ]
    };
});
```
And I have this error : 
```
Exception in queued task: TypeError: Cannot call method 'valueOf' of null
     at [object Object].get (packages/reywood_publish-composite/packages/reywood_publish-composite.js:208:1)
    at [object Object].has (packages/reywood_publish-composite/packages/reywood_publish-composite.js:218:1)
    at Object.added (packages/reywood_publish-composite/packages/reywood_publish-composite.js:67:1)
    at [object Object].observeChangesCallbacks.added (packages/minimongo/observe.js:153:1)
     at self.applyChange.added (packages/minimongo/observe.js:53:1)
    at packages/mongo/observe_multiplex.js:183:1
     at Array.forEach (packages/es5-shim/.npm/package/node_modules/es5-shim/es5-shim.js:417:1)
     at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
     at Object.task (packages/mongo/observe_multiplex.js:177:1)
     at [object Object]._.extend._run (packages/meteor/fiber_helpers.js:147:1)
```
I don't know why, I test Devis.find() return I have data and same with Client.find(), I have data.

**Comment by reywood** [comment]
I'm not near a computer right now, but off the top of my head, it looks like you're returning documents that don't have an `_id` field.

**Comment by GJean** [comment]
Yes, I add _id for Devis and Client but I have the same error.

**Comment by reywood** [comment]
I've looked at the code, and the only way this happens is if the `_id` field has a value of `null`. Note that this is different than the document **not** having an `_id` field.

**Comment by GJean** [comment]
I search in mongo and I find one document with null _id. Thanks for your help.
