### ISSUE TITLE
arbitrary collection name

### ISSUE THREAD

**Issue by timmyg** [englue/meteor-publish-composite#84]
Is it possible to use this package to publish collection with an arbitrary collection name?

My use case is I have two template-level publications on the same route that need to show different data. So that they dont interfere with each other, it looks as though you can do this: http://stackoverflow.com/questions/27748100/in-meteor-how-can-i-query-only-the-records-of-a-given-subscription.

```
    find: ->
      console.log "segment-people-create-campaign", appId, segmentId, options
      return unless options
      SegmentPeople.find { app: OID(appId), segment: OID(segmentId) }, options
    children: [ 
        { 
          find: (segmentPerson) ->
            Mongo.Collection._publishCursor People.find
                _id: segmentPerson.person
                app: segmentPerson.app
            , this, 'people2'
        } 
    ]
```

However, doing so results in this error on server:
```
I20160426-10:16:49.938(-4)? Exception in queued task: Error: Match error: Failed Match.OneOf or Match.Optional validation
I20160426-10:16:49.939(-4)?     at check (packages/check/match.js:33:1)
I20160426-10:16:49.939(-4)?     at [object Object]._.extend._getFindOptions (packages/mongo/collection.js:248:1)
I20160426-10:16:49.940(-4)?     at [object Object]._.extend.find (packages/mongo/collection.js:284:1)
I20160426-10:16:49.940(-4)?     at [object Object].children.find (server/publicationsReactive.coffee:12:52)
I20160426-10:16:49.940(-4)?     at Publication._getCursor (packages/reywood_publish-composite/packages/reywood_publish-composite.js:117:1)
I20160426-10:16:49.941(-4)?     at Publication.publish (packages/reywood_publish-composite/packages/reywood_publish-composite.js:58:1)
```

Any ideas? Thanks!

**Comment by timmyg** [comment]
similar use case to #82

**Comment by timmyg** [comment]
Ah, looks like you can use collectionName.... http://braindump.io/meteor/2014/09/20/publishing-to-an-alternative-clientside-collection-in-meteor.html
